name: Deploy either for staging or production

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies and clean output
      run: |
        rm -rf .output
        npm install
        npm run build

    - name: Copy files
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSH }}
      with:
        source: "./.output"
        target: "/var/www/staging/babble"

    - name: Clean directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH }}
        script: |
          export PATH=$PATH:/home/theo/.nvm/versions/node/v16.13.1/bin
          pm2 restart babble-staging